services:
  - type: web
    name: house-rocket-streamlit
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_final.py --server.port $PORT --server.address 0.0.0.0
